openapi: 3.1.0
info:
  title: Interrogator API 1.0
  description: |-
    This is the Interrogator API for the web client

    Source:
    - [GitHub](https://github.com/ataastar/interrogator-api)

  termsOfService: no any
  contact:
    email: ata.astar@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: No any external docs
  url: a
servers:
  - url: http://localhost:3000
tags:
  - name: unit
    description: Unit related APIs. Unit is a group of translations
  - name: translation
    description: Common (phrase) translation related end points
  - name: auth
    description: Access to the API
  - name: word-type
    description: Can collect words into 'group' by its type. E.g. Irregular verbs
paths:
  /api/login:
    post:
      tags:
        - auth
      summary: Login into the app
      description: Login into the app with saved user data
      operationId: login
      requestBody:
        description: Login
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Unauthorized
  /api/refreshToken:
    post:
      tags:
        - auth
      summary: Refresh the access token
      description: Refresh the access token with the refresh token, so the refresh token is checked during the authentication. It also refreshes the refresh token too
      operationId: refreshToken
      requestBody:
        description: Login
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Unauthorized
      security:
        - jwt_auth:
            - use:API
  /word:
    post:
      tags:
        - translation
      summary: Add new translation to the unit
      description: Add new translation (phrases and links) to the unit
      operationId: addTranslation
      requestBody:
        required: true
        description: Create a new translation in the unit
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslationToSave'
      responses:
        '200':
          description: Successful operation return with the created translation id
          content:
            application/json:
              schema:
                type: integer
                format: int64
                example: 123
      security:
        - jwt_auth:
            - use:API
  /word/{unitContentId}:
    delete:
      tags:
        - translation
      summary: Delete a unit content
      description: Delete a unit content (and the translation if no any reference to it) by unit content id.
      operationId: deleteUnitContent
      parameters:
        - name: unitContentId
          in: path
          description: Unit content id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Success deletion
        '404':
          description: Un success deletion
  /word/{unitId}:
    get:
      tags:
        - translation
      summary: Get the translations for a unit
      description: Get the translations for a unit by unit id
      operationId: getUnitPrhases
      parameters:
        - name: unitId
          in: path
          required: true
          description: The unit id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnitContentWithTranslations'
        '405':
          description: Invalid input
      security:
        - jwt_auth:
            - use:API
  /units:
    get:
      tags:
        - unit
      summary: Get the unit tree
      description: Get the unit tree
      operationId: unitTree
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnitTree'
      security:
        - jwt_auth:
            - use:API
  /word_types/words/{wordTypeId}/{fromLanguageId}/{toLanguageId}:
    get:
      tags:
        - word-type
      summary: Get the translations for a word type
      description: Get the translations for a word type by language ids from-to
      operationId: getWordTypeTranslations
      parameters:
        - name: wordTypeId
          in: path
          required: true
          description: The word type id
          schema:
            type: integer
            format: int64
        - name: fromLanguageId
          in: path
          required: true
          description: The from language id
          schema:
            type: integer
            format: int64
        - name: toLanguageId
          in: path
          required: true
          description: The to language id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WordTypeTranslationResponse'
      security:
        - jwt_auth:
            - use:API
  /word_types/units/words/{wordTypeUnitId}/{fromLanguageId}:
    get:
      tags:
        - word-type
      summary: Get the translations for a word type unit
      description: Get the translations for a word type unit by from language
      operationId: getWordTypeUnitTranslations
      parameters:
        - name: wordTypeUnitId
          in: path
          required: true
          description: The word type unit id
          schema:
            type: integer
            format: int64
        - name: fromLanguageId
          in: path
          required: true
          description: The from language id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WordTypeUnitTranslationResponse'
      security:
        - jwt_auth:
            - use:API
  /word_types/units:
    get:
      tags:
        - word-type
      summary: Get all the word type units
      description: Get all the word type units
      operationId: getWordTypeUnits
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WordTypeUnitTranslationResponse'
      security:
        - jwt_auth:
            - use:API
  /answer:
    post:
      tags:
        - translation
      summary: Store the result of the success of the translation
      description: Store the answer (Store the result of the success of the translation)
      operationId: storeAnswer
      requestBody:
        required: true
        description: Create a new answer for the translation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddAnswerRequest'
      responses:
        '200':
          description: Success answer store
        '404':
          description: Un success answer store
      security:
        - jwt_auth:
            - use:API
  /word_types/units/link:
    put:
      tags:
        - word-type
      summary: Add a word type translation to a word type unit
      description: Add a word type translation to a word type unit
      operationId: AddWordTypeUnitLink
      requestBody:
        required: true
        description: Create a new answer for the translation
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/WordTypeUnitLink'
      responses:
        '200':
          description: Success answer store
        '404':
          description: Un success answer store
      security:
        - jwt_auth:
            - use:API
    delete:
      tags:
        - word-type
      summary: Delete a word type translation from a word type unit
      description: Delete a word type translation from a word type unit
      operationId: DeleteWordTypeUnitLink
      requestBody:
        required: true
        description: Create a new answer for the translation
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/WordTypeUnitLink'
      responses:
        '204':
          description: Success deletion
        '404':
          description: Un success deletion
components:
  requestBodies:
    WordTypeUnitLink:
      required:
        - wordTypeUnitId
        - wordTypeLinkId
      type: object
      properties:
        wordTypeUnitId:
          type: integer
          description: The id of the word type unit
          format: int64
        wordTypeLinkId:
          type: integer
          description: The id of the word type link (word type translation)
          format: int64
  schemas:
    AddAnswerRequest:
      required:
        - unitContentId
        - right
        - interrogationType
      type: object
      properties:
        unitContentId:
          type: integer
          description: The id of the unit content
          format: int64
        right:
          type: [boolean]
          description: The success of the result of the translation
        interrogationType:
          type: string
          description: The interrogation type. Currently just the WRITING enabled
          enum:
            - WRITING
            - TO_BE_DECIDED
    LoginRequest:
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    RefreshTokenRequest:
      required:
        - refreshToken
      type: object
      properties:
        refreshToken:
          type: string
    LoginResponse:
      required:
        - idToken
        - refreshToken
        - roles
      type: object
      properties:
        idToken:
          type: string
          description: The JWT access token
        refreshToken:
          type: string
          description: The JWT refresh token
        roles:
          type: array
          items:
            type: string
            examples:
              - user
              - admin
        nickname:
          type: string
          example: Bob
    UnitContentWithTranslations:
      description: The unit with the translations
      allOf:
        - $ref: '#/components/schemas/UnitLeaf'
        - type: object
          properties:
            words:
              type: array
              items:
                $ref: '#/components/schemas/UnitContent'
    UnitContent:
      required:
        - id
        - from
        - to
      type: object
      description: The translations of the unit with example and calculated interrogation time
      properties:
        id:
          type: integer
          description: The id of the unit content
          format: int64
          example: 10
        from:
          type: array
          items:
            $ref: '#/components/schemas/FromTranslation'
        to:
          type: array
          items:
            $ref: '#/components/schemas/ToTranslation'
        example:
          type: string
          description: An example sentence for the phrase
          example: A kutya ugat
        translatedExample:
          type: string
          description: The translation of the example sentence
          example: The dog barks
        nextInterrogationTime:
          type: string
          format: date-time
          description: The time when the translation will be interrogated
        lastAnswerTime:
          type: string
          format: date-time
          description: The last time when the translation was anwered
    FromTranslation:
      required:
        - translationId
        - phrase
      type: object
      description: The translation from part with id and the connected phrase
      properties:
        translationId:
          type: integer
          description: The id of translation from
          format: int64
          example: 11
        phrase:
          type: string
          example: kutya
    ToTranslation:
      required:
        - translationId
        - phrase
      type: object
      description: The translation to part with id and the connected phrase
      properties:
        translationId:
          type: integer
          description: The id of translation to
          format: int64
          example: 12
        phrase:
          type: string
          example: dog
    TranslationToSave:
      required:
        - id
        - from
        - to
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        example:
          type: string
          example: Example sentence
        translatedExample:
          type: string
          example: The translated example sentence
        from:
          type: array
          items:
            type: string
            examples:
              - phrase to be translated
        to:
          type: array
          items:
            type: string
            examples:
              - The translated phrase
    UnitLeaf:
      type: object
      description: The unit leaf data
      required:
        - name
        - code
      properties:
        name:
          type: string
          example: Unit 1
          description: The name of the unit leaf
        code:
          type: integer
          format: int64
          example: 11
          description: The id of the unit leaf
    UnitTree:
      type: array
      items:
        type: object
        required:
          - name
          - order
        properties:
          name:
            type: string
            example: Unit group 1
            description: The name of the unit group
          order:
            type: integer
            format: int64
            example: 10
            description: The order of the unit group
          group:
            type: array
            items:
              type: object
              $ref: '#/components/schemas/UnitLeaf'
    WordTypeTranslation:
      required:
        - id
        - toPhrases
        - fromPhrases
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123
          description: The id of the word type link (translation)
        toPhrases:
          type: array
          items:
            type: object
            description: The key is the word type form name
            additionalProperties:
              type: array
              items:
                type: string
                description: The translated word
        fromPhrases:
          type: array
          items:
            type: string
            description: The word which is translated
    WordTypeUnitTranslationResponse:
      required:
        - name
        - forms
      type: object
      properties:
        name:
          type: string
          example: Irregular verbs
          description: The name of the word type
        forms:
          type: array
          description: The defined forms of the word type
          items:
            type: string
            description: The word type form
            examples:
              - Verb
              - Past tense
              - Past participle
        rows:
          type: array
          items:
            type: object
            description: The word type link translation data
            $ref: '#/components/schemas/WordTypeTranslation'
    WordTypeTranslationResponse:
      required:
        - name
        - forms
        - wordTypeUnits
      type: object
      properties:
        name:
          type: string
          example: Irregular verbs
          description: The name of the word type
        rows:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/WordTypeTranslation'
              - type: object
                description: The translation data for the word from-to words and the connection to the unit
                properties:
                  wordTypeUnits:
                    type: array
                    items:
                      type: integer
                      format: int64
                      example: 123
                      description: The id of the word type unit, for where the word is added/connected
        forms:
          type: array
          description: The defined forms of the word type
          items:
            type: string
            description: The word type form
            examples:
              - Verb
              - Past tense
              - Past participle
        wordTypeUnits:
          type: array
          items:
            type: object
            description: It is a list of the available unit for the word types, for which the words are connected/linked
            required:
              - name
              - id
            properties:
              name:
                type: string
                description: The name of the word type unit
                example: Part 1
              id:
                type: integer
                format: int64
                example: 123
                description: The id of the word type unit
  securitySchemes:
    jwt_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
